# Generated by Django 6.0.6 on 2026-06-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_purchaseorderlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
