# Generated by Django 6.0.6 on 2026-06-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_purchaseorderattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Rascunho'), ('OPEN', 'Em Aprovação'), ('APPROVED', 'Aprovado'), ('PURCHASED', 'Comprado'), ('RECEIVED', 'Recebido'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=20),
        ),
    ]
